version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend-service
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-service
    depends_on:
      - backend