name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend
      working-directory: ./backend
      run: |
        docker build -t preetham1210/clouddeploypro-backend:latest .
        docker push preetham1210/clouddeploypro-backend:latest
    
    - name: Build and push frontend
      working-directory: ./frontend
      run: |
        docker build -t preetham1210/clouddeploypro-frontend:latest .
        docker push preetham1210/clouddeploypro-frontend:latest